### ISSUE TITLE
check my pull

### ISSUE THREAD

**Issue by obito02** [kataras/pio#2]
i see when buld a dinamyc link library this show a console and not god
to fix

      atributos := &syscall.SysProcAttr{}
	atributos.HideWindow = true
	cmd.SysProcAttr = atributos

terminal.go
terminal_windows.go

**Comment by kataras** [comment]
You didn't open a PR @obito02  this is why I didn't get notified. Sorry, I just see that - I hope I could check that before, thanks for your contribution anyways!
